config/routes.rb
Rails.application.routes.draw do
 
  get 'sections/index'
  get 'sections/show'
  get 'sections/new'
  get 'sections/edit'
  get 'sections/delete'
  
  
  get 'pages/index'
  get 'pages/show'
  get 'pages/new'
  get 'pages/edit'
  get 'pages/delete'
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete'

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end
 
  resources :sections do
    member do
      get :delete
    end
  end
  root 'subjects#index'
  resources :subjects
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

    belongs_to :subject,{:optional=>false}
    has_and_belonds_to_many :admin_users

    scope :visible , lambda { where(:visible =>true) }
    scope :invisible , lambda {where(:visible =>false)}
    scope :sorted , lambda {order("position ASC")}
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def delete
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new({:name => 'defult'})
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] ="Subject Saved Succesfully"
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
      if @subject.update(subject_params)
        flash[:notice] ="Subject updated Succesfully"
        redirect_to(subject_path(@subject))
      else
        render('edit') 
      end
  end

  def delete
    @subject = Subject.find(params[:id])
  end 

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
      flash[:notice] ="Subject Deleted Succesfully"
      redirect_to(subjects_path)
  end


  private
    def subject_params
      params.require(:subject).permit(:name ,:position ,:visible)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/delete.html.erb
<h1>Pages#delete</h1>
<p>Find me in app/views/pages/delete.html.erb</p>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/new.html.erb
<h1>Pages#new</h1>
<p>Find me in app/views/pages/new.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/sections/delete.html.erb
<h1>Sections#delete</h1>
<p>Find me in app/views/sections/delete.html.erb</p>

app/views/sections/edit.html.erb
<h1>Sections#edit</h1>
<p>Find me in app/views/sections/edit.html.erb</p>

app/views/sections/index.html.erb
<h1>Sections#index</h1>
<p>Find me in app/views/sections/index.html.erb</p>

app/views/sections/new.html.erb
<h1>Sections#new</h1>
<p>Find me in app/views/sections/new.html.erb</p>

app/views/sections/show.html.erb
<h1>Sections#show</h1>
<p>Find me in app/views/sections/show.html.erb</p>

app/views/subjects/create.html.erb
<h1>Subject#create</h1>
<p>Find me in app/views/subject/create.html.erb</p>

app/views/subjects/delete.html.erb
<%=link_to("<<Back to List" ,subject_path,:class=>'back-link')%>
<div class="subjects delete">
    <h2>Delete Subject</h2>

    <%= form_for(@subject , :url=>subject_path(@subject) , :method=>'delete')  do |f|%>
        <p>Are You Sure Delete thise Object</P>
        <p class="reference-name"> <%=f.object.name%> </P>
        <div class="form-button">
            <%= f.submit("Delete Subject")%>
        </div>
    <%end%>
</div>

app/views/subjects/destroy.html.erb
<h1>Subject#destroy</h1>
<p>Find me in app/views/subject/destroy.html.erb</p>

app/views/subjects/edit.html.erb
<%= link_to("<<back to list" , subjects_path , :class => 'back_link')%>
<div class="subjects edit">
    <h2>Create Subject</h2>
    <%=form_for(@subject) do |f|%>
    
    <table summary="Subject form field">
        <tr>
            <th>Name</th>
            <td><%=f.text_field(:name)%></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%=f.text_field(:position)%></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%=f.text_field(:visible)%></td>
        </tr>
    </table>
    <div class="form-buttons">
        <%=f.submit("Update Subject")%>
    </div>

    <%end%>
<div>

app/views/subjects/index.html.erb
<% if !flash[:notice].blank?%>
    <div class="notice">
    <%# <%=!flash[:notice].blank?%>
    <%# <%=flash[:notice].blank?%> 
    <%=flash[:notice]%>
    </div>
<%end%>
<div class="Subjects index">
    <h2>Subject Index</h2>
    <%= link_to 'Add new Subject' , new_subject_path , :class => 'action new'%>

    <table class="listening" summary="Subject list">
        <tr class="header">
            <th>#</th>
            <th>Subject</th>
            <th>Visible</th>
            <th>Pages</th>
            <th>Action</th>
        </tr>
        <% @subjects.each do |subject|%>
        <tr>
            <td><%=subject.position%></td>
            <td><%=subject.name%></td>
            <td class="center"><%=subject.visible %></td>
            <td class="center"><%=subject.pages %></td>
            <td>
                <%= link_to("Show" , subject_path(subject) ,:class=>'action show')%>
                <%= link_to("Edit" , edit_subject_path(subject) , :class=>'action edit')%>
                <%= link_to("Delete" , delete_subject_path(subject) , :class=>'action delete' )%>
            </td>
        </tr>
        <%end%>
    </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<<back to list" , subjects_path , :class => 'back_link')%>
<div class="subjects new">
    <h2>Create Subject</h2>
    <%=form_for(@subject) do |f|%>
    
    <table summary="Subject form field">
        <tr>
            <th>Name</th>
            <td><%=f.text_field(:name)%></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%=f.text_field(:position)%></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%=f.text_field(:visible)%></td>
        </tr>
    </table>
    <div class="form-buttons">
        <%=f.submit("Create Subject")%>
    </div>

    <%end%>
<div>

app/views/subjects/show.html.erb
<%= link_to("<<Back to List" , subjects_path , :class=>'back-link')%>
<div class="subject show">
    <h2> Show Subject </h2>
    <table summary="Subject details view">
        <tr>
            <th>Name:</th>
            <td><%= @subject.name%></td>
        </tr>
        <tr>
            <th>Position</th>
            <td><%= @subject.position%></td>
        </tr>
        <tr>
            <th>Visible</th>
            <td><%= @subject.visible%></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><%= @subject.created_at%></td>
        </tr>
        <tr>
            <th>Updated</th>
            <td><%= @subject.updated_at%></td>
        </tr>

    </table>

</div>